{% set version = "0.5.0" %}

package:
  name: wsgiproxy2
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/W/WSGIProxy2/WSGIProxy2-{{ version }}.tar.gz
  sha256: aa6c2e9c470f5045c900bc965c097ca2ef0e76a16e361e2149340b2030c29d37

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - setuptools
    - webob
    - six

test:
  imports:
    - wsgiproxy

about:
  home: https://github.com/gawel/WSGIProxy2
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: A WSGI Proxy with various http client backends
  doc_url: https://wsgiproxy2.readthedocs.org
  dev_url: https://github.com/gawel/WSGIProxy2

extra:
  recipe-maintainers:
    - nehaljwani
