{% set version = "0.4.6" %}

package:
  name: wsgiproxy2
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/W/WSGIProxy2/WSGIProxy2-{{ version }}.tar.gz
  sha256: cee2a64abc193cc96c7ff1208b709335e9a4d1316ce84b91501102166d814c9a

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python
    - pip
  run:
    - python
    - setuptools
    - webob
    - six

test:
  imports:
    - wsgiproxy

about:
  home: https://github.com/gawel/WSGIProxy2
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: A WSGI Proxy with various http client backends
  doc_url: https://wsgiproxy2.readthedocs.org
  dev_url: https://github.com/gawel/WSGIProxy2

extra:
  recipe-maintainers:
    - nehaljwani
